# Generated by Django 3.0.9 on 2020-12-10 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_rule_logic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to=settings.AUTH_USER_MODEL),
        ),
    ]
